{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "names.fullname" . }}
  namespace: {{ include "names.namespace" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
data:
  config.yml: |-
    {{- toYaml .Values.config | nindent 4}}
{{ end }}