apiVersion: v1
kind: Service
metadata:
  name: {{ include "names.fullname" . }}
  namespace: {{ include "names.namespace" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 31088
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-ui.selectorLabels" . | nindent 4 }}
