apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.configmapName" . }}
  namespace: {{ include "names.namespace" . | quote }}
data:
  # KRaft 模式配置
  KAFKA_PROCESS_ROLES: "controller,broker"
  KAFKA_CONTROLLER_QUORUM_VOTERS: {{ include "kafka.kraft.controllerQuorumVoters" . }}

  # 网络配置
  KAFKA_LISTENERS: {{ include "kafka.listeners" . }}
  KAFKA_ADVERTISED_LISTENERS: {{ include "kafka.advertisedListeners" . }}
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: {{ include "kafka.securityProtocolMap" . }}
  KAFKA_INTER_BROKER_LISTENER_NAME: {{ .Values.listeners.interbroker.name }}

  # 控制器配置
  KAFKA_CONTROLLER_LISTENER_NAMES: {{ .Values.listeners.controller.name }}

  # 存储配置
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"

  # 集群配置
  KAFKA_DEFAULT_REPLICATION_FACTOR: "3"
  KAFKA_MIN_INSYNC_REPLICAS: "2"

  # 其他优化
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
