apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "names.namespace" . | quote }}
  labels: {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-interbroker
      port: {{ .Values.service.ports.interbroker }}
      protocol: TCP
      targetPort: interbroker
    - name: tcp-client
      port: {{ .Values.service.ports.client }}
      protocol: TCP
      targetPort: client
    - name: tcp-controller
      protocol: TCP
      port: {{ .Values.service.ports.controller }}
      targetPort: controller
  selector: {{- include "kafka.selectorLabels" . | nindent 4 }}
